# Generated by Django 5.0.9 on 2024-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('module_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('modules', models.ManyToManyField(blank=True, help_text='Modules assigned to this role.', related_name='role_modules', to='module_group.module', verbose_name='modules')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role.', related_name='role_permissions', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'permissions': [('can_delete_user', 'Can delete user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_export_users', 'Can export users'), ('can_import_users', 'Can import users'), ('can_detail_user', 'Can detail user'), ('can_delete_department', 'Can delete department'), ('can_add_department', 'Can add department'), ('can_edit_department', 'Can edit department'), ('can_detail_department', 'Can detail department')],
                'default_permissions': (),
            },
        ),
    ]
