# Generated by Django 5.0.9 on 2024-10-25 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_Truong', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='course_Truong.newcourse'),
        ),
        migrations.AddField(
            model_name='enrolled_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='course_Truong.newcourse'),
        ),
        migrations.AddField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='course_Truong.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course_Truong.quiz'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='course_Truong.question'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='course_Truong.answer_option'),
        ),
        migrations.AddField(
            model_name='ai_grading',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_gradings', to='course_Truong.student_answer'),
        ),
        migrations.AddField(
            model_name='student_quiz_attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='course_Truong.quiz'),
        ),
        migrations.AddField(
            model_name='student_quiz_attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='course_Truong.student_quiz_attempt'),
        ),
        migrations.AddField(
            model_name='sub_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='course_Truong.newcourse'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sub_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course_Truong.sub_course'),
        ),
        migrations.AddField(
            model_name='module',
            name='sub_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course_Truong.sub_course'),
        ),
        migrations.AddField(
            model_name='sub_module',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_modules', to='course_Truong.module'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolled_course',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='sub_course',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('order', 'sub_course')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('order', 'sub_course')},
        ),
        migrations.AlterUniqueTogether(
            name='sub_module',
            unique_together={('order', 'module')},
        ),
    ]
